import { accent, compositeEmitted, fg, hex, neutral, overlay } from '@sltsh/aion-tokens';

export const HERDR_VERSION = '0.9.0';

const selection = compositeEmitted(overlay.selection.color, overlay.selection.alpha, neutral.editor);

export const herdrColours = (): Record<string, string> => ({
  accent: hex(accent.gold.solid),
  panel_bg: hex(neutral.widget),
  sidebar_bg: hex(neutral.sidebar),
  active_row_bg: hex(neutral.input),
  selection_bg: hex(selection),
  surface0: hex(neutral.input),
  surface1: hex(neutral.hover),
  surface_dim: hex(neutral.hairline),
  overlay0: hex(fg.comment),
  overlay1: hex(fg.secondary),
  text: hex(fg.primary),
  subtext0: hex(fg.comment),
  mauve: hex(accent.violet.solid),
  green: hex(accent.green.solid),
  yellow: hex(accent.gold.solid),
  red: hex(accent.coral.solid),
  blue: hex(accent.blue.solid),
  teal: hex(accent.teal.solid),
  peach: hex(accent.copper.solid),
});

export const herdrConfig = (): string => [
  `# Aion for Herdr ${HERDR_VERSION}.`,
  '# Merge these tables into the matching sections of your Herdr config.',
  '# Generated by packages/terminal from the Aion tokens; do not edit.',
  '',
  '[theme]',
  'name = "one-dark"',
  'auto_switch = false',
  '',
  '[theme.custom]',
  ...Object.entries(herdrColours()).map(([key, value]) => `${key} = "${value}"`),
  '',
].join('\n');
