import type { Oklch, Palette } from '@sltsh/aion-tokens';
export const SITE_PAIRS: readonly { fg: string; bg: string; floor: 4.5 | 3; where: string }[] = [
  { fg: '--aion-border-ui', bg: '--aion-bg-raised', floor: 3, where: 'Solved strip tile edge against card' },
  ...(['gold', 'coral', 'copper', 'green', 'teal', 'blue', 'violet'] as const).map(accent => ({
    fg: `--aion-${accent}-solid`, bg: '--aion-bg-raised', floor: 4.5 as const, where: `Solved ${accent} accent name`,
  })),
  { fg: '--n-text-primary', bg: '--n-editor', floor: 4.5, where: 'Palette file and chart labels; install tile name' },
  { fg: '--n-text-secondary', bg: '--n-editor', floor: 4.5, where: 'Palette guides and uses; install channel' },
  { fg: '--n-text-primary', bg: '--n-sidebar', floor: 4.5, where: 'install command and Copy label' },
  { fg: '--n-text-primary', bg: '--n-sidebar', floor: 4.5, where: 'install badge label and glyph' },
  { fg: '--n-border', bg: '--n-editor', floor: 3, where: 'install badge edge on tile' },
  { fg: '--n-border', bg: '--n-sidebar', floor: 3, where: 'install badge edge on badge surface' },
  { fg: '--a-gold', bg: '--n-editor', floor: 3, where: 'install badge hover and focus edge on tile' },
  { fg: '--a-gold', bg: '--n-sidebar', floor: 3, where: 'install badge hover edge on badge surface' },
  { fg: '--aion-status-success-solid', bg: '--n-sidebar', floor: 4.5, where: 'install Copied state' },
  { fg: '--aion-status-success-text', bg: '--aion-bg-surface', floor: 4.5, where: 'States positive delta' },
  { fg: '--aion-status-error-text', bg: '--aion-bg-surface', floor: 4.5, where: 'States negative delta' },
  { fg: '--n-border', bg: '--n-sidebar', floor: 3, where: 'States toolbar control edge' },
  { fg: '--a-gold', bg: '--n-sidebar', floor: 3, where: 'States toolbar active control edge' },
  { fg: '--aion-fg-primary', bg: '--aion-bg-surface', floor: 4.5, where: 'States meters and Terminal slot labels' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-surface', floor: 4.5, where: 'States background label and Terminal slot ratio labels' },
  { fg: '--n-text-secondary', bg: '--n-sidebar', floor: 4.5, where: 'States toolbar labels' },
  { fg: '--n-text-primary', bg: '--n-sidebar', floor: 4.5, where: 'States toolbar active labels' },
  { fg: '--aion-fg-primary', bg: '--aion-bg-raised', floor: 4.5, where: 'Solved and Rounded chip labels, verdict and dimension text' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-raised', floor: 4.5, where: 'Solved and Rounded secondary labels' },
  { fg: '--aion-status-success-text', bg: '--aion-bg-raised', floor: 4.5, where: 'Solved and Rounded passing verdict' },
  { fg: '--aion-status-error-text', bg: '--aion-bg-raised', floor: 4.5, where: 'Solved and Rounded failing verdict' },

  { fg: '--aion-fg-primary', bg: '--aion-bg-surface', floor: 4.5, where: 'claim card text, Depth part tags and ruler labels' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-surface', floor: 4.5, where: 'claim card descriptions and ruler ratios' },
  { fg: '--aion-fg-primary', bg: '--aion-bg-surface', floor: 4.5, where: 'page and headings' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-surface', floor: 4.5, where: 'page copy' },
  { fg: '--aion-fg-primary', bg: '--aion-bg-raised', floor: 4.5, where: 'controls and tabs' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-raised', floor: 4.5, where: 'editor bar and command metadata' },
  { fg: '--aion-fg-dim', bg: '--aion-bg-raised', floor: 4.5, where: 'disabled copy controls' },
  { fg: '--aion-fg-primary', bg: '--aion-bg-page', floor: 4.5, where: 'swatch copy controls' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-page', floor: 4.5, where: 'editor footer' },
  { fg: '--aion-gold-solid', bg: '--aion-bg-surface', floor: 4.5, where: 'site links' },
  { fg: '--aion-fg-on-accent', bg: '--aion-gold-solid', floor: 4.5, where: 'primary buttons' },
  { fg: '--aion-fg-on-accent', bg: '--aion-fg-primary', floor: 4.5, where: 'primary button hover' },
  { fg: '--aion-teal-solid', bg: '--aion-bg-raised', floor: 4.5, where: 'editor badge' },
  { fg: '--aion-status-success-solid', bg: '--aion-bg-surface', floor: 4.5, where: 'copy confirmation' },
  { fg: '--aion-border-focus', bg: '--aion-bg-surface', floor: 3, where: 'page focus edge' },
  { fg: '--aion-border-ui', bg: '--aion-bg-raised', floor: 3, where: 'copy control edge' },
  { fg: '--a-gold', bg: '--n-editor', floor: 3, where: 'dimension origin key' },
  { fg: '--n-text-secondary', bg: '--n-editor', floor: 4.5, where: 'dimension label' },
  { fg: '--status-error-text', bg: '--n-editor', floor: 4.5, where: 'dimension error label' },
  { fg: '--n-text-primary', bg: '--n-editor', floor: 4.5, where: 'chip labels on their own scheme halves' },
  { fg: '--a-gold', bg: '--n-editor', floor: 3, where: 'chip active gold key on each scheme half' },
  { fg: '--aion-fg-secondary', bg: '--aion-bg-surface', floor: 4.5, where: 'header nav links' },
  { fg: '--aion-fg-primary', bg: '--aion-bg-surface', floor: 4.5, where: 'header nav current text' },
  { fg: '--aion-gold-solid', bg: '--aion-bg-surface', floor: 3, where: 'header nav underline' },
  { fg: '--n-text-primary', bg: '--n-editor', floor: 4.5, where: 'hero headline and secondary CTA' },
  { fg: '--n-text-secondary', bg: '--n-editor', floor: 4.5, where: 'hero sub and header' },
  { fg: '--n-editor', bg: '--a-gold', floor: 4.5, where: 'hero primary CTA' },
  { fg: '--n-editor', bg: '--a-gold', floor: 4.5, where: 'splash wordmark plate' },
  ...(['keyword', 'function', 'type', 'string', 'number', 'variable', 'operator', 'comment'] as const).map((role) => ({
    fg: '--n-editor', bg: `--s-${role}`, floor: 4.5 as const, where: `splash ${role} label`,
  })),
  { fg: '--n-text-primary', bg: '--n-widget', floor: 4.5, where: 'hero handle labels' },
  { fg: '--a-gold', bg: '--n-editor', floor: 3, where: 'hero seam on both editor surfaces' },
];

export function terminalPairs(source: Palette, backgrounds: readonly { name: string; oklch: Oklch }[]): readonly { fg: Oklch; bg: Oklch; floor: 4.5; where: string }[] {
  const slots = ['white', 'brightBlack', 'green', 'blue', 'cyan', 'red', 'yellow', 'magenta', 'brightGreen', 'brightRed'] as const;
  return backgrounds.flatMap(background => slots.map(slot => ({ fg: source.ansi[slot], bg: background.oklch, floor: 4.5 as const, where: `Terminal session ${slot} on ${background.name}` })));
}
