import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dark, light } from './variables.js';
import type { Variables } from './variables.js';

const HEADER = `/* Aion — generated by @sltio/aion-css. Do not edit.
   Change the OKLCH definition in @sltio/aion-tokens and rebuild. */\n`;

const block = (selector: string, extra: string, variables: Variables): string => {
  const body = Object.entries(variables).map(([name, value]) => `  ${name}: ${value};`).join('\n');
  return `${selector} {\n${extra}${body}\n}\n`;
};

const BASE = `
html {
  background-color: var(--aion-bg-page);
  color: var(--aion-fg-primary);
  accent-color: var(--aion-gold-solid);
  caret-color: var(--aion-caret);
}

body { background-color: inherit; color: inherit; }

::selection { background-color: var(--aion-overlay-selection); }

::placeholder { color: var(--aion-fg-secondary); opacity: 1; }

:focus-visible {
  outline: 2px solid var(--aion-border-focus);
  outline-offset: 2px;
}

a { color: var(--aion-fg-link); }
a:hover { color: var(--aion-teal-solid); }

hr { border: 0; border-top: 1px solid var(--aion-border-divider); }

small, .aion-dim { color: var(--aion-fg-dim); }

code, kbd, samp, pre {
  background-color: var(--aion-bg-surface);
  color: var(--aion-fg-primary);
}

pre { border: 1px solid var(--aion-border-hairline); }

kbd {
  border: 1px solid var(--aion-border-hairline);
  border-bottom-color: var(--aion-border-divider);
}

mark {
  background-color: var(--aion-overlay-find-match);
  color: var(--aion-fg-primary);
}

blockquote {
  border-left: 2px solid var(--aion-teal-border);
  color: var(--aion-fg-secondary);
}

table { border-collapse: collapse; }
th, td { border-bottom: 1px solid var(--aion-border-hairline); }
th { color: var(--aion-fg-primary); }
td { color: var(--aion-fg-secondary); }

input, textarea, select {
  background-color: var(--aion-bg-input);
  color: var(--aion-fg-primary);
  border: 1px solid var(--aion-border-hairline);
}

button {
  background-color: var(--aion-gold-solid);
  color: var(--aion-fg-on-accent);
  border: 1px solid transparent;
}

button:hover { background-color: var(--aion-gold-solid); filter: brightness(1.08); }

button[data-variant="secondary"] {
  background-color: var(--aion-bg-input);
  color: var(--aion-fg-primary);
  border-color: var(--aion-border-hairline);
}
`;

const css = (): string => [
  HEADER,
  block(':root', '  color-scheme: dark;\n', dark()),
  `\n@media (prefers-color-scheme: light) {\n${block(':root:not([data-theme])', '  color-scheme: light;\n', light())
    .split('\n').map((line) => (line ? `  ${line}` : line)).join('\n')}}\n`,
  `\n${block('[data-theme="light"]', '  color-scheme: light;\n', light())}`,
  `\n${block('[data-theme="dark"]', '  color-scheme: dark;\n', dark())}`,
  BASE,
].join('');

const themeBlock = (): string => {
  const names = Object.keys(dark());
  const colours = names
    .filter((name) => !name.startsWith('--aion-overlay'))
    .map((name) => `  --color-${name.replace('--aion-', '')}: var(${name});`)
    .join('\n');
  return `${HEADER}
/* Import aion.css first. These utilities read its custom properties, so a Tailwind class
   follows the active colour scheme instead of freezing one of them. */
@theme {
${colours}
}
`;
};

const write = (relative: string, contents: string): void => {
  const target = fileURLToPath(new URL(relative, import.meta.url));
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
  console.log(`${relative.replace('../', '')}  ${contents.split('\n').length} lines`);
};

write('../css/aion.css', css());
write('../css/aion.theme.css', themeBlock());
