import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dark, light } from './variables.js';
import type { Variables } from './variables.js';

const HEADER = `/* Aion — generated by @sltio/aion-css. Do not edit.
   Change the OKLCH definition in @sltio/aion-tokens and rebuild. */\n`;

const block = (selector: string, extra: string, variables: Variables): string => {
  const body = Object.entries(variables).map(([name, value]) => `  ${name}: ${value};`).join('\n');
  return `${selector} {\n${extra}${body}\n}\n`;
};

// Every element rule lives in the `base` layer. Tailwind v4 puts its utilities in the
// `utilities` layer, and an unlayered rule beats any layered one whatever its specificity,
// so an unlayered `button` background won `bg-bg-raised` on a button. The variable blocks
// stay unlayered: they are definitions a consumer overrides directly.
const BASE = `
@layer base {
  html {
    background-color: var(--aion-bg-page);
    color: var(--aion-fg-primary);
    accent-color: var(--aion-gold-solid);
    caret-color: var(--aion-caret);
  }

  body { background-color: inherit; color: inherit; }

  /* The selection replaces the foreground as well as the background. Solving one overlay
     that keeps every foreground this sheet ships above the floor would take a light
     selection to within a step of the page, so the pair is measured instead: primary text
     on the selection, on every surface the selection can land on. */
  ::selection {
    background-color: var(--aion-overlay-selection);
    color: var(--aion-fg-primary);
  }

  ::placeholder { color: var(--aion-fg-secondary); opacity: 1; }

  :focus-visible {
    outline: 2px solid var(--aion-border-focus);
    outline-offset: 2px;
  }

  a { color: var(--aion-fg-link); }
  a:hover { color: var(--aion-teal-solid); }

  hr { border: 0; border-top: 1px solid var(--aion-border-divider); }

  small, .aion-dim { color: var(--aion-fg-dim); }

  code, kbd, samp, pre {
    background-color: var(--aion-bg-surface);
    color: var(--aion-fg-primary);
  }

  pre { border: 1px solid var(--aion-border-hairline); }

  kbd {
    border: 1px solid var(--aion-border-hairline);
    border-bottom-color: var(--aion-border-divider);
  }

  mark {
    background-color: var(--aion-overlay-find-match);
    color: var(--aion-fg-primary);
  }

  blockquote {
    border-left: 2px solid var(--aion-teal-border);
    color: var(--aion-fg-secondary);
  }

  table { border-collapse: collapse; }
  th, td { border-bottom: 1px solid var(--aion-border-hairline); }
  th { color: var(--aion-fg-primary); }
  td { color: var(--aion-fg-secondary); }

  /* A control edge is functional, not decorative, so it uses the UI border rather than the
     hairline. The hairline read 1.41:1 against the dark field and 1.21:1 against the light
     one, which is no edge at all for anyone finding the control by keyboard. */
  input, textarea, select {
    background-color: var(--aion-bg-input);
    color: var(--aion-fg-primary);
    border: 1px solid var(--aion-border-ui);
  }

  button {
    background-color: var(--aion-gold-solid);
    color: var(--aion-fg-on-accent);
    border: 1px solid transparent;
  }

  button:hover { background-color: var(--aion-gold-solid); filter: brightness(1.08); }

  button[data-variant="secondary"] {
    background-color: var(--aion-bg-input);
    color: var(--aion-fg-primary);
    border-color: var(--aion-border-ui);
  }
}
`;

const css = (): string => [
  HEADER,
  block(':root', '  color-scheme: dark;\n', dark()),
  `\n@media (prefers-color-scheme: light) {\n${block(':root:not([data-theme])', '  color-scheme: light;\n', light())
    .split('\n').map((line) => (line ? `  ${line}` : line)).join('\n')}}\n`,
  `\n${block('[data-theme="light"]', '  color-scheme: light;\n', light())}`,
  `\n${block('[data-theme="dark"]', '  color-scheme: dark;\n', dark())}`,
  BASE,
].join('');

const themeBlock = (): string => {
  const names = Object.keys(dark());
  const colours = names
    .filter((name) => !name.startsWith('--aion-overlay'))
    .map((name) => `  --color-${name.replace('--aion-', '')}: var(${name});`)
    .join('\n');
  return `${HEADER}
/* Import aion.css first. These utilities read its custom properties, so a Tailwind class
   follows the active colour scheme instead of freezing one of them.

   The inline keyword is what makes that true inside a nested [data-theme] region. A
   plain @theme alias resolves where it is defined, at the root, and a utility on an
   element inside a light region then inherits the root's dark value. An inline alias
   substitutes the var() into the utility, so it resolves at the consuming element. */
@theme inline {
${colours}
}
`;
};

const write = (relative: string, contents: string): void => {
  const target = fileURLToPath(new URL(relative, import.meta.url));
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
  console.log(`${relative.replace('../', '')}  ${contents.split('\n').length} lines`);
};

write('../css/aion.css', css());
write('../css/aion.theme.css', themeBlock());
